'use client';

import { motion } from 'framer-motion';
import { Trophy, Zap, TrendingUp } from 'lucide-react';
import { ENSBadge } from './ENSBadge';

interface AgentRaceCardProps {
  agentId: string;
  ensName: string;
  apy: number;
  proposal: string;
  progress: number; // 0-100
  isWinner?: boolean;
  rank: number;
}

export function AgentRaceCard({
  agentId,
  ensName,
  apy,
  proposal,
  progress,
  isWinner = false,
  rank,
}: AgentRaceCardProps) {
  return (
    <motion.div
      initial={{ opacity: 0, x: -50 }}
      animate={{ opacity: 1, x: 0 }}
      className={`
        relative p-6 rounded-xl border-2
        ${isWinner 
          ? 'border-green-500 bg-green-50 dark:bg-green-900/20 shadow-lg shadow-green-500/50' 
          : 'border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800'
        }
        overflow-hidden
      `}
    >
      {isWinner && (
        <motion.div
          initial={{ scale: 0, rotate: -180 }}
          animate={{ scale: 1, rotate: 0 }}
          className="absolute top-4 right-4"
        >
          <Trophy className="h-8 w-8 text-yellow-500" />
        </motion.div>
      )}

      <div className="flex items-start justify-between mb-4">
        <div className="flex items-center gap-3">
          <div className={`
            w-12 h-12 rounded-full flex items-center justify-center text-white font-bold
            ${isWinner ? 'bg-gradient-to-br from-green-400 to-green-600' : 'bg-gradient-to-br from-indigo-400 to-purple-600'}
          `}>
            #{rank}
          </div>
          <div>
            <ENSBadge name={ensName} size="sm" />
            <p className="text-xs text-gray-600 dark:text-gray-400 mt-1">{agentId}</p>
          </div>
        </div>
        <div className="text-right">
          <div className="text-3xl font-bold text-green-600 dark:text-green-400 flex items-center gap-1">
            <TrendingUp className="h-5 w-5" />
            {apy}%
          </div>
          <p className="text-xs text-gray-600 dark:text-gray-400">Expected APY</p>
        </div>
      </div>

      <div className="mb-4">
        <p className="text-sm text-gray-700 dark:text-gray-300 mb-2">{proposal}</p>
        <div className="flex items-center gap-2 text-xs text-gray-600 dark:text-gray-400">
          <Zap className="h-3 w-3" />
          <span>Strategy generated by Llama 3.2</span>
        </div>
      </div>

      <div>
        <div className="flex justify-between text-xs text-gray-600 dark:text-gray-400 mb-1">
          <span>Progress</span>
          <span>{progress}%</span>
        </div>
        <div className="w-full h-2 bg-gray-200 dark:bg-gray-700 rounded-full overflow-hidden">
          <motion.div
            initial={{ width: 0 }}
            animate={{ width: `${progress}%` }}
            transition={{ duration: 1, ease: 'easeOut' }}
            className={`h-full rounded-full ${
              isWinner 
                ? 'bg-gradient-to-r from-green-400 to-green-600' 
                : 'bg-gradient-to-r from-indigo-400 to-purple-600'
            }`}
          />
        </div>
      </div>
    </motion.div>
  );
}

